# Generated by Django 5.2.12 on 2026-04-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('CONTACT_FORM', 'Contact Form'), ('CHATBOT', 'Chatbot'), ('PROPERTY_INQUIRY', 'Property Inquiry'), ('NEWSLETTER', 'Newsletter'), ('VALUATION', "What's My Home Worth")], max_length=20),
        ),
    ]
