# Generated by Django 5.2.12 on 2026-04-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_add_valuation_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='budget',
            field=models.CharField(blank=True, help_text='e.g. $200,000 - $400,000', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_type_interest',
            field=models.CharField(blank=True, help_text='e.g. 3BHK apartment, house, land', max_length=100),
        ),
    ]
