# Generated by Django 5.2.12 on 2026-04-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_add_budget_property_type_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='property_image_1',
            field=models.ImageField(blank=True, help_text='Property image 1', null=True, upload_to='leads/property_images/'),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_image_2',
            field=models.ImageField(blank=True, help_text='Property image 2', null=True, upload_to='leads/property_images/'),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_image_3',
            field=models.ImageField(blank=True, help_text='Property image 3', null=True, upload_to='leads/property_images/'),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_image_4',
            field=models.ImageField(blank=True, help_text='Property image 4', null=True, upload_to='leads/property_images/'),
        ),
        migrations.AddField(
            model_name='lead',
            name='property_image_5',
            field=models.ImageField(blank=True, help_text='Property image 5', null=True, upload_to='leads/property_images/'),
        ),
    ]
