# Generated by Django 5.2.12 on 2026-05-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='avatar_image',
            field=models.ImageField(blank=True, help_text='Upload an image file. If provided, this takes priority over the URL field above.', null=True, upload_to='agents/avatars/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='avatar',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
