# Generated by Django 6.0.5 on 2026-05-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_add_avatar_image_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='quote',
            field=models.TextField(blank=True, help_text='Personal quote or motto'),
        ),
    ]
