# Generated by Django 5.2.12 on 2026-04-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('images', models.JSONField(default=list, help_text='List of image URLs')),
                ('location', models.CharField(max_length=200)),
                ('completion_date', models.DateField()),
                ('category', models.CharField(default='Residential', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-completion_date'],
                'indexes': [models.Index(fields=['-completion_date'], name='projects_pr_complet_fe728c_idx'), models.Index(fields=['is_featured'], name='projects_pr_is_feat_bfabaf_idx')],
            },
        ),
    ]
