# Generated by Django 5.2.12 on 2026-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectimage_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsHeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Projects', max_length=200)),
                ('subtitle', models.CharField(default='Your exquisite partners in finding home solutions', help_text='Subtitle text displayed below the title', max_length=300)),
                ('background_image', models.ImageField(blank=True, help_text='Hero background image (recommended: 1920x600px)', null=True, upload_to='projects/heroes/')),
                ('background_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=1920', help_text='Fallback to URL if no image uploaded', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projects Hero Settings',
                'verbose_name_plural': 'Projects Hero Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
