# Generated by Django 5.2.12 on 2026-04-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
        ('blog', '0008_delete_bloggalleryimage'),
    ]

    operations = [
    ]
