# Generated by Django 5.2.12 on 2026-04-28 08:43

from django.db import migrations


def copy_bloggalleryimage_data(apps, schema_editor):
    """Copy data from blog_bloggalleryimage to gallery_galleryimage"""
    # Use raw SQL to copy data from the old table to the new table
    # This will only work if the blog_bloggalleryimage table still exists
    try:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                INSERT INTO gallery_galleryimage 
                (id, post_id, image, caption, alt_text, "order", created_at)
                SELECT id, post_id, image, caption, alt_text, "order", created_at
                FROM blog_bloggalleryimage
            """)
    except Exception:
        # Table doesn't exist or data already copied, skip
        pass


def reverse_copy(apps, schema_editor):
    """Delete copied data"""
    GalleryImage = apps.get_model('gallery', 'GalleryImage')
    GalleryImage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_migrate_bloggalleryimage_to_galleryimage'),
    ]

    operations = [
        migrations.RunPython(copy_bloggalleryimage_data, reverse_copy),
    ]
