# Generated by Django 5.2.12 on 2026-04-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Upload a custom logo image (optional)', null=True, upload_to='cms/logos/'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Upload a custom logo image (optional)', null=True, upload_to='cms/logos/'),
        ),
    ]
