# Generated by Django 5.2.12 on 2026-04-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_footersettings_logo_image_headersettings_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Subscribe to my newsletter', max_length=200)),
                ('description', models.TextField(default='Get the most recent information on real estate.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Newsletter Settings',
                'verbose_name_plural': 'Newsletter Settings',
            },
        ),
    ]
