# Generated by Django 5.2.12 on 2026-04-23 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('cms', '0003_newslettersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySidebarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_title', models.CharField(default='Contact For Your Real Estate Solutions', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('default_agent', models.ForeignKey(blank=True, help_text='Default agent to display in property sidebar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sidebar_settings', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Property Sidebar Settings',
                'verbose_name_plural': 'Property Sidebar Settings',
            },
        ),
    ]
