# Generated by Django 5.2.12 on 2026-04-23 19:23

from django.db import migrations


def update_branding(apps, schema_editor):
    """Update all Realtor Pal references to Lily White Realestate"""
    HeaderSettings = apps.get_model('cms', 'HeaderSettings')
    FooterSettings = apps.get_model('cms', 'FooterSettings')
    
    # Update header settings
    HeaderSettings.objects.filter(logo_text='Realtor Pal').update(
        logo_text='Lily White Realestate'
    )
    
    # Update footer settings
    FooterSettings.objects.filter(logo_text='Realtor Pal').update(
        logo_text='Lily White Realestate'
    )
    FooterSettings.objects.filter(copyright_text__contains='Realtor Pal').update(
        copyright_text='2026 Lily White Realestate. All rights reserved.'
    )


def reverse_branding(apps, schema_editor):
    """Reverse the branding update"""
    HeaderSettings = apps.get_model('cms', 'HeaderSettings')
    FooterSettings = apps.get_model('cms', 'FooterSettings')
    
    # Reverse header settings
    HeaderSettings.objects.filter(logo_text='Lily White Realestate').update(
        logo_text='Realtor Pal'
    )
    
    # Reverse footer settings
    FooterSettings.objects.filter(logo_text='Lily White Realestate').update(
        logo_text='Realtor Pal'
    )
    FooterSettings.objects.filter(copyright_text__contains='Lily White Realestate').update(
        copyright_text='2026 Realtor Pal. All rights reserved.'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_propertysidebarsettings'),
    ]

    operations = [
        migrations.RunPython(update_branding, reverse_branding),
    ]
