# Generated by Django 6.0.5 on 2026-05-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_propertiesherosettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Upload site favicon (recommended: 32x32px or 64x64px .ico, .png)', null=True, upload_to='cms/favicons/'),
        ),
        migrations.AddField(
            model_name='headersettings',
            name='site_name',
            field=models.CharField(default='Lily White Realestate', help_text='Site name for browser tab and SEO', max_length=100),
        ),
    ]
