# Generated by Django 5.2.12 on 2026-04-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question or topic customers ask about.', max_length=500)),
                ('answer', models.TextField(help_text='The full answer the chatbot will give. Use plain text.')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated trigger words/phrases. Example: hours, open, working hours, office hours. Leave blank to auto-detect from the question.', max_length=500)),
                ('category', models.CharField(choices=[('general', 'General'), ('services', 'Services'), ('pricing', 'Pricing'), ('process', 'Process'), ('legal', 'Legal'), ('contact', 'Contact & Hours'), ('properties', 'Properties'), ('financing', 'Financing'), ('buying', 'Buying'), ('selling', 'Selling'), ('renting', 'Renting'), ('about', 'About Us'), ('policies', 'Policies'), ('other', 'Other')], default='general', max_length=50)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = checked first. Use to prioritise important answers.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge Base Entry',
                'verbose_name_plural': 'Knowledge Base',
                'ordering': ['-priority', 'question'],
            },
        ),
    ]
