# Generated by Django 5.2.12 on 2026-04-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_knowledge_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this rule (not shown to users).', max_length=200)),
                ('pattern', models.CharField(help_text="The pattern to match against the user message (case-insensitive). For 'contains': enter a word or phrase. For 'regex': enter a valid Python regex. Examples: 'hello', 'book a viewing', r'\\d+ bedroom'", max_length=500)),
                ('match_type', models.CharField(choices=[('exact', 'Exact match  — message equals pattern exactly'), ('contains', 'Contains     — message contains the pattern'), ('startswith', 'Starts with  — message starts with the pattern'), ('endswith', 'Ends with    — message ends with the pattern'), ('regex', 'Regex        — full Python regex pattern')], default='contains', max_length=20)),
                ('response', models.TextField(help_text='The response to send when this rule matches. Use [icon] markers for Lucide icons, e.g. [phone], [home], [check-circle].')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher number = evaluated first. Rules with same priority are sorted by name.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chatbot Rule',
                'verbose_name_plural': 'Chatbot Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
