# Generated by Django 5.2.12 on 2026-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatbot_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='chatbotrule',
            name='name',
            field=models.CharField(help_text='Internal name for this rule.', max_length=200),
        ),
        migrations.AlterField(
            model_name='chatbotrule',
            name='pattern',
            field=models.CharField(help_text='Pattern to match against the user message.', max_length=500),
        ),
        migrations.AlterField(
            model_name='chatbotrule',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher = evaluated first.'),
        ),
        migrations.AlterField(
            model_name='chatbotrule',
            name='response',
            field=models.TextField(help_text='Response to send when this rule matches.'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='answer',
            field=models.TextField(help_text='The full answer the chatbot will give.'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated trigger words.', max_length=500),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher = checked first.'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='question',
            field=models.CharField(help_text='The question customers ask.', max_length=500),
        ),
    ]
