# Generated by Django 6.0.5 on 2026-05-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_chatbotsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotsettings',
            name='tawk_enabled',
            field=models.BooleanField(default=False, help_text='Enable or disable the Tawk.to live chat.'),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='tawk_property_id',
            field=models.CharField(blank=True, help_text='Tawk.to Property ID (found in embed URL: embed.tawk.to/[PROPERTY_ID]/...)', max_length=100),
        ),
        migrations.AddField(
            model_name='chatbotsettings',
            name='tawk_widget_id',
            field=models.CharField(blank=True, help_text='Tawk.to Widget ID (found in embed URL: embed.tawk.to/.../[WIDGET_ID])', max_length=100),
        ),
        migrations.AlterField(
            model_name='chatbotsettings',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable the custom AI chatbot in the frontend.'),
        ),
    ]
