# Generated by Django 5.2.12 on 2026-04-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'CALL ME', 'OFFICE ADDRESS', 'EMAIL ME'", max_length=100)),
                ('value', models.CharField(help_text="e.g., '+1 (321) 456 7890', '324 King Avenue, Boston, USA'", max_length=200)),
                ('icon', models.CharField(choices=[('phone', 'Phone'), ('map', 'Map Pin'), ('email', 'Email')], default='phone', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Card',
                'verbose_name_plural': 'Contact Cards',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.TextField(default="If you have any questions about the real estate market, I'd love to chat. Reach out below, and I'll get back to you shortly. I look forward to hearing from you.", help_text='Text displayed above the contact cards')),
                ('agent_name', models.CharField(default='Justin Nelson', max_length=100)),
                ('agent_title', models.CharField(default='Boston Realtor', max_length=100)),
                ('agent_image', models.URLField(default='https://www.realtorpal.hocud.com/wp-content/uploads/Realtor-Pal-Main-Agent-pro.png', help_text='URL to agent profile image', max_length=500)),
                ('facebook_url', models.URLField(blank=True, default='#')),
                ('twitter_url', models.URLField(blank=True, default='#')),
                ('instagram_url', models.URLField(blank=True, default='#')),
                ('linkedin_url', models.URLField(blank=True, default='#')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Form Settings',
                'verbose_name_plural': 'Contact Form Settings',
            },
        ),
    ]
