# Generated by Django 5.2.12 on 2026-04-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsettings',
            name='agent_image',
            field=models.ImageField(blank=True, help_text='Upload agent profile image', null=True, upload_to='contact/agents/'),
        ),
    ]
