# Generated by Django 5.2.12 on 2026-04-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="URL-friendly identifier (e.g., 'buy-property')", max_length=200, unique=True)),
                ('description', models.TextField(help_text='Main description text')),
                ('image', models.ImageField(help_text='Service image (recommended: 640x700px)', upload_to='services/')),
                ('layout', models.CharField(choices=[('IMAGE_LEFT', 'Image on Left'), ('IMAGE_RIGHT', 'Image on Right')], default='IMAGE_LEFT', max_length=20)),
                ('phone', models.CharField(default='+1 (321) 456 7890', max_length=50)),
                ('email', models.EmailField(default='hello@example.com', max_length=254)),
                ('button_text', models.CharField(default='Contact Me', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this service')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='services_se_order_c72088_idx'), models.Index(fields=['is_active'], name='services_se_is_acti_91b7ea_idx'), models.Index(fields=['slug'], name='services_se_slug_4657d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Feature',
                'verbose_name_plural': 'Service Features',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
