# Generated by Django 6.0.5 on 2026-05-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide an external image URL (used if no image is uploaded)', max_length=500),
        ),
        migrations.AddField(
            model_name='servicesherosettings',
            name='background_image',
            field=models.ImageField(blank=True, help_text='Upload a background image for the services hero section', null=True, upload_to='services/hero/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a service image', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicesherosettings',
            name='background_url',
            field=models.URLField(blank=True, default='https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=1920', help_text='Or provide an external image URL (used if no image is uploaded)', max_length=500),
        ),
    ]
