# Generated by Django 6.0.5 on 2026-05-07 10:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
