# Generated by Django 5.2.12 on 2026-04-21 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short description for listing pages', max_length=500)),
                ('content', models.TextField(help_text='Full blog post content (supports HTML)')),
                ('featured_image', models.URLField(max_length=500)),
                ('author_name', models.CharField(default='Admin', max_length=100)),
                ('author_avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(default='Real Estate', max_length=100)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags')),
                ('views', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='blog_blogpo_publish_e75c11_idx'), models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'), models.Index(fields=['category'], name='blog_blogpo_categor_481d67_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_email', models.EmailField(max_length=254)),
                ('author_avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('SPAM', 'Spam')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'status'], name='blog_commen_post_id_651007_idx'), models.Index(fields=['-created_at'], name='blog_commen_created_1f5393_idx')],
            },
        ),
    ]
