# Generated by Django 5.2.12 on 2026-04-23 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author_avatar',
            field=models.ImageField(blank=True, help_text='Author avatar image', null=True, upload_to='blog/avatars/'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Featured image for the blog post', null=True, upload_to='blog/featured/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_avatar',
            field=models.ImageField(blank=True, help_text='Comment author avatar', null=True, upload_to='blog/comment_avatars/'),
        ),
        migrations.CreateModel(
            name='BlogGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image', upload_to='blog/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
