# Generated by Django 5.2.12 on 2026-04-23 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_convert_category_to_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloggalleryimage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_publish_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_categor_481d67_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogpost',
            name='blog_blogpo_categor_idx',
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['category'], name='blog_blogpo_categor_c7bd72_idx'),
        ),
        migrations.AddField(
            model_name='bloggalleryimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200),
        ),
        migrations.AlterField(
            model_name='bloggalleryimage',
            name='image',
            field=models.ImageField(help_text='Upload image', upload_to='blog/gallery/'),
        ),
        migrations.AlterField(
            model_name='bloggalleryimage',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='blog.blogpost'),
        ),
    ]
