# Generated by Django 5.2.12 on 2026-04-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogherosettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogGalleryImage',
        ),
    ]
