# Generated by Django 6.0.5 on 2026-05-06 10:45

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_bloggalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Full blog post content with rich text editor'),
        ),
    ]
