# Generated by Django 5.2.12 on 2026-04-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertiesHeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Properties', max_length=200)),
                ('subtitle', models.CharField(default='Find your dream homes with me.', max_length=300)),
                ('background_image', models.ImageField(blank=True, help_text='Hero background image (recommended: 1920x600px)', null=True, upload_to='properties/heroes/')),
                ('background_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1920', help_text='Fallback to URL if no image uploaded', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Properties Hero Settings',
                'verbose_name_plural': 'Properties Hero Settings',
            },
        ),
    ]
