# Generated by Django 5.2.12 on 2026-04-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertiesherosettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertiesherosettings',
            options={'verbose_name': 'Hero Settings', 'verbose_name_plural': '⚙️ Hero Settings'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at'], 'verbose_name': 'Property', 'verbose_name_plural': '🏠 Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertyimage',
            options={'ordering': ['order'], 'verbose_name': 'Property Image', 'verbose_name_plural': '📷 Property Images'},
        ),
    ]
