# Generated by Django 5.2.12 on 2026-05-03 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('INTERIOR', 'Interior Features'), ('EXTERIOR', 'Exterior Features'), ('APPLIANCES', 'Appliances'), ('UTILITIES', 'Utilities'), ('COMMUNITY', 'Community Features'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('name', models.CharField(help_text="Feature name (e.g., 'Hardwood Floors', 'Central AC')", max_length=100)),
                ('icon', models.CharField(blank=True, help_text="Optional icon name (e.g., 'home', 'car', 'tree')", max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Feature',
                'verbose_name_plural': 'Property Features',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
