# Generated by Django 6.0.5 on 2026-05-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertyfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertiesherosettings',
            name='bedroom_options',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of {value, label} objects. E.g. [{"value":"1","label":"1+"}]'),
        ),
        migrations.AddField(
            model_name='propertiesherosettings',
            name='filter_title',
            field=models.CharField(blank=True, default='Filters', help_text='Mobile toggle button label', max_length=100),
        ),
        migrations.AddField(
            model_name='propertiesherosettings',
            name='max_price_options',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of {value, label} objects. E.g. [{"value":"200000","label":"$200K"}]'),
        ),
        migrations.AddField(
            model_name='propertiesherosettings',
            name='min_price_options',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of {value, label} objects. E.g. [{"value":"100000","label":"$100K"}]'),
        ),
        migrations.AddField(
            model_name='propertiesherosettings',
            name='property_types',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of {value, label} objects. E.g. [{"value":"HOUSE","label":"House"},{"value":"APARTMENT","label":"Apartment"}]'),
        ),
        migrations.AddField(
            model_name='propertiesherosettings',
            name='show_filters',
            field=models.BooleanField(default=True, help_text='Show or hide the property filter bar'),
        ),
        migrations.AddField(
            model_name='propertiesherosettings',
            name='status_options',
            field=models.JSONField(blank=True, default=list, help_text='JSON list of {value, label} objects. E.g. [{"value":"CURRENT","label":"Current"}]'),
        ),
    ]
