# Generated by Django 6.0.5 on 2026-05-11 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_add_filter_config_to_hero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertiesherosettings',
            options={'verbose_name': 'Properties Hero Settings', 'verbose_name_plural': 'Properties Hero Settings'},
        ),
        migrations.RemoveField(
            model_name='propertiesherosettings',
            name='bedroom_options',
        ),
        migrations.RemoveField(
            model_name='propertiesherosettings',
            name='max_price_options',
        ),
        migrations.RemoveField(
            model_name='propertiesherosettings',
            name='min_price_options',
        ),
        migrations.RemoveField(
            model_name='propertiesherosettings',
            name='property_types',
        ),
        migrations.RemoveField(
            model_name='propertiesherosettings',
            name='status_options',
        ),
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PROPERTY_TYPE', 'Property Type'), ('MIN_PRICE', 'Min Price'), ('MAX_PRICE', 'Max Price'), ('BEDROOMS', 'Bedrooms'), ('STATUS', 'Listing Status')], help_text='The dropdown this option belongs to', max_length=20)),
                ('label', models.CharField(help_text="The text shown to the user (e.g. '$200,000' or '3+ Beds')", max_length=100)),
                ('value', models.CharField(help_text="The internal value sent to the API (e.g. '200000' or '3')", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sort order in the dropdown')),
                ('hero_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_options', to='properties.propertiesherosettings')),
            ],
            options={
                'verbose_name': 'Filter Option',
                'verbose_name_plural': 'Filter Options',
                'ordering': ['category', 'order', 'label'],
            },
        ),
    ]
