# Generated by Django 6.0.5 on 2026-05-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_alter_propertiesherosettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPropertyFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=120, unique=True)),
                ('agent_id', models.CharField(blank=True, default='', max_length=80)),
                ('listing_type', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(db_index=True, default='CURRENT', max_length=40)),
                ('property_type', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('headline', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('formatted_address', models.CharField(blank=True, default='', max_length=400)),
                ('suburb', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=120)),
                ('postcode', models.CharField(blank=True, default='', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('advertised_price', models.CharField(blank=True, default='', max_length=300)),
                ('land_size', models.CharField(blank=True, default='', max_length=80)),
                ('land_size_units', models.CharField(blank=True, default='', max_length=40)),
                ('featured', models.BooleanField(default=False)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('garages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('agent_name', models.CharField(blank=True, default='', max_length=200)),
                ('agent_email', models.EmailField(blank=True, default='', max_length=254)),
                ('agent_phone', models.CharField(blank=True, default='', max_length=80)),
                ('agent_mobile', models.CharField(blank=True, default='', max_length=80)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('floorplan_urls', models.JSONField(blank=True, default=list)),
                ('inspection_times', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Property Feed',
                'verbose_name_plural': 'External Property Feeds',
                'ordering': ['-updated_at'],
            },
        ),
    ]
