# Generated by Django 5.2.12 on 2026-04-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Benefits - Benefit Item', 'verbose_name_plural': 'Benefits - Benefit Items'},
        ),
        migrations.AlterModelOptions(
            name='benefitgalleryimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Benefits - Gallery Image', 'verbose_name_plural': 'Benefits - Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='benefitscontactinfo',
            options={'verbose_name': 'Benefits - Contact Info & Gallery', 'verbose_name_plural': 'Benefits - Contact Info & Gallery'},
        ),
    ]
