# Generated by Django 5.2.12 on 2026-04-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_benefit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Benefit Item', 'verbose_name_plural': 'Benefit Items'},
        ),
        migrations.AlterModelOptions(
            name='benefitgalleryimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='benefitscontactinfo',
            options={'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contact Info'},
        ),
    ]
