# Generated by Django 5.2.12 on 2026-04-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_benefit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Benefits Section - Benefit Item', 'verbose_name_plural': 'Benefits Section - Benefit Items'},
        ),
        migrations.AlterModelOptions(
            name='benefitgalleryimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Benefits Section - Gallery Image', 'verbose_name_plural': 'Benefits Section - Gallery Images'},
        ),
        migrations.AlterModelOptions(
            name='benefitscontactinfo',
            options={'verbose_name': 'Benefits Section - Contact Info', 'verbose_name_plural': 'Benefits Section - Contact Info'},
        ),
    ]
