# Generated by Django 5.2.12 on 2026-04-23 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_benefit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Choose Us', max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Benefits Section',
                'verbose_name_plural': 'Benefits Section',
            },
        ),
        migrations.DeleteModel(
            name='BenefitsContactInfo',
        ),
        migrations.AlterModelOptions(
            name='benefit',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Benefit Item', 'verbose_name_plural': 'Benefit Items'},
        ),
        migrations.AlterModelOptions(
            name='benefitgalleryimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AddField(
            model_name='benefit',
            name='benefits_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='home.benefitssection'),
        ),
        migrations.AddField(
            model_name='benefitgalleryimage',
            name='benefits_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='home.benefitssection'),
        ),
    ]
