# Generated by Django 5.2.12 on 2026-04-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_benefitssection_delete_benefitscontactinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefitssection',
            name='description',
            field=models.TextField(default='My objective is to not only have a good impact on ourselves and our families but also to inspire, encourage, and affect long-term change in everyone we meet.'),
        ),
    ]
