# Generated by Django 5.2.12 on 2026-04-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWorthFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_title', models.CharField(default='Request Your Free Home Valuation', help_text='Main form heading', max_length=200)),
                ('form_description', models.TextField(default="Fill out the form below and I'll provide you with a comprehensive market analysis of your property.", help_text='Description text below the form title')),
                ('submit_button_text', models.CharField(default='GET FREE VALUATION', help_text='Text displayed on the submit button', max_length=100)),
                ('success_message', models.TextField(default="Thank you! Your valuation request has been submitted. We'll contact you shortly.", help_text='Message shown after successful form submission')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Worth Form Settings',
                'verbose_name_plural': 'Home Worth Form Settings',
            },
        ),
        migrations.CreateModel(
            name='HomeWorthHeroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="What's My Home Worth?", max_length=200)),
                ('subtitle', models.CharField(default='Get a free, accurate valuation of your property', help_text='Subtitle text displayed below the title', max_length=300)),
                ('background_image', models.ImageField(blank=True, help_text='Hero background image (recommended: 1920x600px)', null=True, upload_to='homeworth/heroes/')),
                ('background_image_url', models.URLField(blank=True, default='https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&q=80&w=1920', help_text='Fallback to URL if no image uploaded', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Worth Hero Settings',
                'verbose_name_plural': 'Home Worth Hero Settings',
            },
        ),
    ]
