# Generated by Django 5.2.12 on 2026-04-21 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField(help_text='Testimonial text')),
                ('property_type', models.CharField(blank=True, help_text='What they bought/sold/rented', max_length=100, null=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL for video testimonials', max_length=500, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_approved', 'is_featured'], name='testimonial_is_appr_289d45_idx'), models.Index(fields=['-created_at'], name='testimonial_created_f57fe8_idx')],
            },
        ),
    ]
