# Generated by Django 5.2.12 on 2026-04-23 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Testimonial title (e.g., 'Brilliant Service')", max_length=200)),
                ('name', models.CharField(help_text='Client name', max_length=100)),
                ('role', models.CharField(choices=[('BUYER', 'Happy Buyer'), ('SELLER', 'Happy Seller'), ('RENTER', 'Happy Renter'), ('LANDLORD', 'Happy Landlord')], default='BUYER', help_text='Client role', max_length=20)),
                ('text', models.TextField(help_text='Testimonial content')),
                ('image', models.ImageField(blank=True, help_text='Client photo', null=True, upload_to='testimonials/')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL for video testimonials', max_length=500, null=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Show on website')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature on homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['is_approved', 'is_featured'], name='testimonial_is_appr_289d45_idx'), models.Index(fields=['order', '-created_at'], name='testimonial_order_22d46b_idx')],
            },
        ),
    ]
