# Generated by Django 5.0.1 on 2026-04-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_testimonialsherosettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonialsherosettings',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Testimonials Hero Settings', 'verbose_name_plural': 'Testimonials Hero Settings'},
        ),
    ]
